# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

brews:
  name: pure
  goarm: 6
  tap:
    owener: Am3o
    name: homerbrew-tap
  url_template: "https://github.com/Am3o/pure/releases/{{ .Tag }}/{{ .ArtifactName }}"
  download_strategy: CurlDownloadStrategy.
  commit_author:
    name: Am3o
    email: jbraun@inovex.de
  folder: Formula
  description: "Software for experimental create fast and easy drum rolls."
  license: "MIT"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
